//
//  FirebaseEvents.swift
//  colatour
//
//  Created by M7268 on 2019/4/23.
//  Copyright © 2019 Colatour. All rights reserved.
//

enum Event : String {
    case HOME_LAUNCH_START = "home_launch_start"
    case PUSH_AGREE = "push_agree"
    case PUSH_DISAGREE = "push_disagree"
    case HOME_SET_PUSH = "home_set_push"
    case DM = "dm"
    case TICKET_HOME_VIEW = "ticket_home_view"
    case TICKET_SELECT_CITY = "ticket_select_city"
    case TICKET_RECENTLY_VIEW = "ticket_recently_view"
    case APPHOME_AD = "apphome_ad"
    case TICKET_HOME_AD = "ticket_home_ad"
    case TICKET_CITY_VIEW_LIST = "ticket_city_view_list"
    case TICKET_CITY_VIEW_ALL = "ticket_city_view_all"
    case TICKET_SEARCH_BEGIN = "ticket_search_begin"
    case TICKET_SEARCH_INPUT = "ticket_search_input"
    case TICKET_SEARCH_VIEW_RESULT = "ticket_search_view_result"
    case TICKET_SEARCH_CLICK_RESULT = "ticket_search_click_result"
    case TICKET_SEARCH_RECENTLY = "ticket_search_recently"
    case TICKET_COUNTRY_VIEW_LIST = "ticket_country_view_list"
    case TICKET_CATAGORY_VIEW_LIST = "ticket_catagory_view_list"
    case TICKET_HOT_VIEW = "ticket_hot_view"
    case TICKET_VIEW = "ticket_view"
    case TICKET_REMARK_VIEW = "ticket_remark_view"
    case TICKET_LIKE = "ticket_like"
    case TICKET_SHARE = "ticket_share"
    case TICKET_PROMO_VIEW = "ticket_promo_view"
    case TICKET_SUPPLIER_VIEW = "ticket_supplier_view"
    case TICKET_CART_ADD_BEGIN = "ticket_cart_add_begin"
    case TICKET_CART_ADD_SELECT_DATE = "ticket_cart_add_select_date"
    case TICKET_CART_ADD_COMPLETE = "ticket_cart_add_complete"
    case TICKET_CART_VIEW = "ticket_cart_view"
    case TICKET_CART_UPDATE = "ticket_cart_update"
    case TICKET_CART_DELETE = "ticket_cart_delete"
    case TICKET_ORDER_BEGIN = "ticket_order_begin"
    case TICKET_ORDER_CHANGE = "ticket_order_change"
    case TICKET_ORDER_PASSENGER = "ticket_order_passenger"
    case TICKET_ORDER_SEND = "ticket_order_send"
    case PAY_BEGIN = "pay_begin"
    case PAY_DELIVERY = "pay_delivery"
    case PAY_ATM = "pay_atm"
    case PAY_COMPLETE = "pay_complete"
    case SIGN_IN_BEGIN = "sign_in_begin"
    case SIGN_IN = "sign_in"
    case SIGN_OUT = "sign_out"
    case SIGN_UP_BEGIN = "sign_up_begin"
    case SIGN_UP = "sign_up"
    case SIGN_IN_PASSENGER = "sign_in_passenger"
    case MEMBER_UPDATE = "member_update"
    case PASSWORD_UPDATE = "password_update"
    case ORDER_VIEW_LIST = "order_view_list"
    case ORDER_VIEW = "order_view"
    case ORDER_SET_PAX = "order_set_pax"
    case MEMBER_POLICY_VIEW = "member_policy_view"
    case FQL_VIEW_LIST = "fql_view_list"
    case STORE_VIEW_LIST = "store_view_list"
    case PRIVATE_VIEW = "private_view"
    case QUESTION_SEND = "question_send"
    case PAX_VIEW_LIST = "pax_view_list"
    case PAX_ADD = "pax_add"
    case PAX_UPDATE = "pax_update"
    case PAX_REMOVE = "pax_remove"
    case ETICKET_VIEW_LIST = "eticket_view_list"
    case ETICKET_VIEW = "eticket_view"
    case ETICKET_VIEW_FILE = "eticket_view_file"
    case LIKE_VIEW_LIST = "like_view_list"
    case LIKE_VIEW = "like_view"
    case PROMOTION_VIEW_LIST = "promotion_view_list"
    case PROMOTION_BINDING = "promotion_binding"
    case BT_BENEFIT_VIEW_LIST = "bt_benefit_view_list"
    case BT_BENEFIT_VIEW = "bt_benefit_view"
    case NOTI_VIEW_LIST = "noti_view_list"
    case NOTI_REMOVE = "noti_remove"
    case NOTI_VIEW = "noti_view"
    case SCHEDULE_VIEW_LIST = "schedule_view_list"
    case SCHEDULE_VIEW = "schedule_view"
    case SCHEDULE_SHARE = "schedule_share"
    case SCHEDULE_GET_ROUTE = "schedule_get_route"
    case SCHEDULE_NOW_LOCATION = "schedule_now_location"
    case SCHEDULE_VIEW_ALL = "schedule_view_all"
    case SCHEDULE_VIEW_MAP = "schedule_view_map"
    case SCHEDULE_ADD = "schedule_add"
    case SCHEDULE_UPDATE = "schedule_update"
    case HOTEL_SEARCH_VIEW_LIST = "hotel_search_view_list"
    case HOTEL_DETAIL_VIEW = "hotel_detail_view"
    case HOTEL_LIST_SORT = "hotel_list_sort"
    case HOTEL_LIST_MAP_VIEW = "hotel_list_map_view"
    case HOTEL_LIST_FILTER = "hotel_list_filter"
    case HOTEL_DETAIL_LIKE = "hotel_detail_like"
    case HOTEL_DETAIL_SHARE = "hotel_detail_share"
    case HOTEL_DETAIL_TRAFFIC_VIEW = "hotel_detail_traffic_view"
    case HOTEL_DETAIL_NOTICE_VIEW = "hotel_detail_notice_view"
    case HOTEL_DETAIL_PHOTO_VIEW = "hotel_detail_photo_view"
    case HOTEL_DETAIL_PRICE_LIST = "hotel_detail_price_list"
    case HOTEL_DETAIL_CHANGE_SEARCH = "hotel_detail_change_search"
    case HOTEL_DETAIL_PRICE_FILTER = "hotel_detail_price_filter"
    case HOTEL_HOME_VIEW = "hotel_home_view"
    case HOTEL_RECENTLY_SEARCH = "hotel_recently_search"
    case HOTEL_HOME_AD = "hotel_home_ad"
    case HOTEL_SELECT_DATE = "hotel_select_date"
    case HOTEL_SELECE_PEOPLE = "hotel_select_people"
    case HOTEL_SEARCH_VIEW = "hotel_search_view"
    case HOTEL_SEARCH_SELECT_CITY = "hotel_search_select_city"
    case HOTEL_SEARCH_INPUT = "hotel_search_input"
    case HOTEL_ORDER_BEGIN = "hotel_order_begin"
    case HOTEL_ORDER_FILL_DATA = "hotel_order_fill_data"
    case HOTEL_ORDER_RETURN = "hotel_order_return"
    case HOTEL_ORDER_ERROR = "hotel_order_error"
    case HOTEL_ORDER_COMPLETE = "hotel_order_complete"
}

enum EventParameter : String {
    case item_id = "item_id"
    case item_name = "item_name"
    case source = "source"
    case item_type = "item_type"
    case item_type2 = "item_type2"
    case item_type3 = "item_type3"
    case item_number = "item_number"
    case item_number2 = "item_number2"
}
